### PR TITLE
Update to use Node 12 V8 APIs

### LINKED ISSUE #76: Upgrade to Node 12
There are a number of breaking changes in the V8 API that require updates to compile for Node 12.

### PR DESCRIPTION
**Pull request by kriszyp**
Fixes #76 .

### CODE REVIEW

**Comment by pierrec** [comment]
Does this also work with node 10?

**Comment by kriszyp** [comment]
Yes, I think so. At least it seems to compile fine for me on Node v10 (the build doesn't look like it is setup to run on Windows, so I didn't test out the compiled files). Are you seeing any compile errors with this? I actually tested it on Node v8.x too, and it seemed to compile fine there as well.

**Comment by vihanb** [comment]
This breaks backwards compatibility!! Noticed all of a sudden my builds started failing on Node<v8 and that's because `v8::Maybe` doesn't have `ToChecked` on older node versions

**Comment by vihanb** [comment]
Should be able to change it to `FromJust` to fix this issue: https://v8docs.nodesource.com/node-6.12/d9/d4b/classv8_1_1_maybe.html#ad97c01315c73bf49b522c2996638a2d2

**Comment by vihanb** [comment]
Created PR #85 to address this.

**Comment by kriszyp** [comment]
What version was this failing on? I tested all the way back to version 8, and I am curious if there was something wrong with my testing (using nvm-windows), or if this affects an older version?

**Comment by kriszyp** [comment]
#85 compiles and tests fine on my node v12, so 👍 from me.

**Comment by vihanb** [comment]
@kriszyp specific version on CI was v6 but looking at source code I believe all node version below 8 don't have the ToChecked alias for v8::Maybe

**Comment by kriszyp** [comment]
@vihanb my apologies for not testing back to v6, glad you were able to get it fixed.

**Pull request merged**
